/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserRole } from '../../models/user-role';

export interface GetAllModerators$Params {
  PageNumber?: number | null;
  PageSize?: number | null;
  SearchTerm?: string | null;
  RoleFilter?: UserRole | null;
  IsActive?: boolean | null;
}

export function getAllModerators(http: HttpClient, rootUrl: string, params?: GetAllModerators$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getAllModerators.PATH, 'get');
  if (params) {
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('RoleFilter', params.RoleFilter, {});
    rb.query('IsActive', params.IsActive, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getAllModerators.PATH = '/api/Moderators';
