#!/usr/bin/env node
// Speckit CLI wrapper (Unix)
const { spawnSync } = require('child_process');
const path = require('path');

const script = path.join(__dirname, 'speckit.js');
const result = spawnSync(process.execPath, [script, ...process.argv.slice(2)], { stdio: 'inherit' });
process.exit(result.status);
