/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResultOfGuid } from '../../models/result-of-guid';
import { SubscribeToNewsletterCommand } from '../../models/subscribe-to-newsletter-command';

export interface Subscribe$Params {
      body: SubscribeToNewsletterCommand
}

export function subscribe(http: HttpClient, rootUrl: string, params: Subscribe$Params, context?: HttpContext): Observable<StrictHttpResponse<ResultOfGuid>> {
  const rb = new RequestBuilder(rootUrl, subscribe.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResultOfGuid>;
    })
  );
}

subscribe.PATH = '/api/Newsletters/subscribe';
