/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompleteQuizAttemptCommand } from '../../models/complete-quiz-attempt-command';

export interface CompleteAttempt$Params {
  attemptId: string;
      body: CompleteQuizAttemptCommand
}

export function completeAttempt(http: HttpClient, rootUrl: string, params: CompleteAttempt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, completeAttempt.PATH, 'put');
  if (params) {
    rb.path('attemptId', params.attemptId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

completeAttempt.PATH = '/api/QuizAttempts/complete/{attemptId}';
