/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetNearestMosque$Params {
  Lat: number;
  Lng: number;
  IsActive?: boolean | null;
  IsVerified?: boolean | null;
}

export function getNearestMosque(http: HttpClient, rootUrl: string, params: GetNearestMosque$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getNearestMosque.PATH, 'get');
  if (params) {
    rb.query('Lat', params.Lat, {});
    rb.query('Lng', params.Lng, {});
    rb.query('IsActive', params.IsActive, {});
    rb.query('IsVerified', params.IsVerified, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getNearestMosque.PATH = '/api/Mosques/nearest';
