/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Language } from '../../models/language';
import { LessonType } from '../../models/lesson-type';

export interface GetLessonsWithPagination$Params {
  CourseId?: string | null;
  PageNumber?: number | null;
  PageSize?: number | null;
  SearchTerm?: string | null;
  IsPublished?: boolean | null;
  Type?: LessonType | null;
  Language?: Language | null;
}

export function getLessonsWithPagination(http: HttpClient, rootUrl: string, params?: GetLessonsWithPagination$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getLessonsWithPagination.PATH, 'get');
  if (params) {
    rb.query('CourseId', params.CourseId, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('IsPublished', params.IsPublished, {});
    rb.query('Type', params.Type, {});
    rb.query('Language', params.Language, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getLessonsWithPagination.PATH = '/api/Lessons';
