/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseProgressDto } from '../../models/course-progress-dto';

export interface GetCourseProgress$Params {
  courseId: string;
}

export function getCourseProgress(http: HttpClient, rootUrl: string, params: GetCourseProgress$Params, context?: HttpContext): Observable<StrictHttpResponse<CourseProgressDto>> {
  const rb = new RequestBuilder(rootUrl, getCourseProgress.PATH, 'get');
  if (params) {
    rb.path('courseId', params.courseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CourseProgressDto>;
    })
  );
}

getCourseProgress.PATH = '/api/Progress/course/{courseId}';
