/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportReason } from '../../models/report-reason';
import { ReportStatus } from '../../models/report-status';
import { ReportType } from '../../models/report-type';

export interface GetAllReports$Params {
  PageNumber?: number | null;
  PageSize?: number | null;
  SearchTerm?: string | null;
  Status?: ReportStatus | null;
  ReportType?: ReportType | null;
  Reason?: ReportReason | null;
  ReportedByUserId?: string | null;
}

export function getAllReports(http: HttpClient, rootUrl: string, params?: GetAllReports$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getAllReports.PATH, 'get');
  if (params) {
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('Status', params.Status, {});
    rb.query('ReportType', params.ReportType, {});
    rb.query('Reason', params.Reason, {});
    rb.query('ReportedByUserId', params.ReportedByUserId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getAllReports.PATH = '/api/Reports';
