/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventStatus } from '../../models/event-status';

export interface GetEventsWithPagination$Params {
  IsPublished?: boolean | null;
  EventStatus?: EventStatus | null;
  From?: string | null;
  To?: string | null;
  PageNumber?: number | null;
  PageSize?: number | null;
  SearchTerm?: string | null;
}

export function getEventsWithPagination(http: HttpClient, rootUrl: string, params?: GetEventsWithPagination$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getEventsWithPagination.PATH, 'get');
  if (params) {
    rb.query('IsPublished', params.IsPublished, {});
    rb.query('EventStatus', params.EventStatus, {});
    rb.query('From', params.From, {});
    rb.query('To', params.To, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('SearchTerm', params.SearchTerm, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getEventsWithPagination.PATH = '/api/Events';
