/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingInquiryRequestStatus } from '../../models/meeting-inquiry-request-status';

export interface GetByModerator$Params {
  moderatorId: string;
  status?: MeetingInquiryRequestStatus | null;
}

export function getByModerator(http: HttpClient, rootUrl: string, params: GetByModerator$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getByModerator.PATH, 'get');
  if (params) {
    rb.path('moderatorId', params.moderatorId, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getByModerator.PATH = '/api/InquiryRequests/by-moderator/{moderatorId}';
