/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddMuslimTubeChannelCommand {
  channelUrlOrId?: string;
  fetchVideosImmediately?: boolean;
  initialVideoLimit?: number;
}
