/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReligiousStatus } from '../models/religious-status';
import { UserRole } from '../models/user-role';
export interface AuthenticationResponse {
  email?: string;
  expiresAt?: string;
  firstName?: string;
  lastName?: string;
  refreshToken?: string;
  refreshTokenExpiresAt?: string;
  religiousStatus?: ReligiousStatus | null;
  role?: UserRole;
  token?: string;
  userId?: string;
}
