/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizAnswerDto } from '../models/quiz-answer-dto';
export interface CompleteQuizAttemptCommand {
  answers?: Array<QuizAnswerDto>;
}
