/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompleteLessonCommand {
  courseId?: string;
  lessonId?: string;
  markAsRead?: boolean;
  progressPercentage?: number | null;
}
