/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseProgressDto {
  completedLessonsCount?: number;
  isCompleted?: boolean;
  progressPercentage?: number;
  totalLessonsCount?: number;
}
