/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAdminCommand {
  bio?: string | null;
  email?: string;
  firstName?: string;
  imageUrl?: string | null;
  lastName?: string;
  password?: string;
  phoneNumber?: string | null;
  role?: string;
}
