/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QaTranslationInput } from '../models/qa-translation-input';
export interface CreateQaCommand {
  isPublished?: boolean;
  tagIds?: Array<string>;
  translations?: Array<QaTranslationInput>;
}
