/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAchievementCommand {
  activeVolunteers?: number;
  coursesCompleted?: number;
  dialogues?: number;
  eventsHeld?: number;
  hijriMonth?: number;
  hijriYear?: number;
  newMuslims?: number;
  socialMediaReach?: number;
}
