/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportReason } from '../models/report-reason';
import { ReportType } from '../models/report-type';
export interface CreateReportCommand {
  description?: string;
  reason?: ReportReason;
  reportType?: ReportType;
  reportedContentId?: string | null;
}
