/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from '../models/language';
import { LearnIslamKnowledgeLevel } from '../models/learn-islam-knowledge-level';
export interface CreateLearnIslamRequestCommand {
  country?: string;
  currentReligion?: string | null;
  email?: string;
  fullName?: string;
  knowledgeLevel?: LearnIslamKnowledgeLevel;
  message?: string | null;
  preferredLanguage?: Language;
}
