/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStudentProfileCommand {
  address?: string | null;
  bio?: string | null;
  country?: string | null;
  countryCode?: string | null;
  dateOfBirth?: string | null;
  dateOfIslamConversion?: string | null;
  oldReligion?: string | null;
  phoneNumber?: string | null;
  reasonForConversion?: string | null;
  reasonOfReligion?: string | null;
}
