/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface CreateEventCommand {
  description?: string | null;
  endDateTime?: string;
  imageUrl?: string | null;
  isPublished?: boolean;
  meetingLink?: string | null;
  speakerName?: string | null;
  startDateTime?: string;
  targetRole?: UserRole | null;
  title?: string;
}
