/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOptionCommand {
  explanation?: string | null;
  isCorrect?: boolean;
  questionId?: string;
  text?: string;
}
