/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from '../models/language';
export interface CreateCourseCommand {
  description?: string | null;
  isPublished?: boolean;
  language?: Language;
  levelId?: string;
  order?: number;
  tagIds?: Array<string>;
  thumbnailUrl?: string | null;
  title?: string;
}
