/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStudentQuestionCommand {
  lessonId?: string;
  questionText?: string;
  studentId?: string;
  timestamp?: number;
}
