/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from '../models/language';
import { LessonType } from '../models/lesson-type';
export interface CreateLessonCommand {
  contentJson?: string | null;
  contentUrl?: string | null;
  courseId?: string;
  description?: string | null;
  duration?: string | null;
  isPublished?: boolean;
  language?: Language;
  order?: number;
  thumbnailUrl?: string | null;
  title?: string;
  transcript?: string | null;
  type?: LessonType;
}
