/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStudentNoteCommand {
  lessonId?: string;
  studentId?: string;
  text?: string;
  timestamp?: number;
}
