/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateFormFieldCommand } from '../models/create-form-field-command';
export interface CreateFormCommand {
  description?: string | null;
  fields?: Array<CreateFormFieldCommand>;
  isPublished?: boolean;
  title?: string;
}
