/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VolunteerType } from '../models/volunteer-type';
export interface CreateVolunteerCommand {
  cvFile?: Blob | null;
  email?: string;
  message?: string;
  name?: string;
  phone?: string;
  type?: VolunteerType;
}
