/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from '../models/language';
import { MeetingInquiryTopic } from '../models/meeting-inquiry-topic';
export interface CreateMeetingRequestCommand {
  languages?: Array<Language>;
  message?: string;
  scheduledAt?: string;
  topic?: MeetingInquiryTopic;
}
