/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnrollmentStatus } from './enrollment-status';

/**
 * Each possible value of `EnrollmentStatus`
 */
export const ENROLLMENT_STATUS: EnrollmentStatus[] = [
  EnrollmentStatus.Active,
  EnrollmentStatus.Completed,
  EnrollmentStatus.Cancelled,
  EnrollmentStatus.Paused
];