/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventRegistrationStatus } from './event-registration-status';

/**
 * Each possible value of `EventRegistrationStatus`
 */
export const EVENT_REGISTRATION_STATUS: EventRegistrationStatus[] = [
  1,
  2,
  3,
  4
];