/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventStatus } from './event-status';

/**
 * Each possible value of `EventStatus`
 */
export const EVENT_STATUS: EventStatus[] = [
  1,
  2,
  3,
  4
];