/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormFieldType } from './form-field-type';

/**
 * Each possible value of `FormFieldType`
 */
export const FORM_FIELD_TYPE: FormFieldType[] = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9
];