/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from './language';

/**
 * Each possible value of `Language`
 */
export const LANGUAGE: Language[] = [
  1,
  2,
  3,
  4,
  5,
  6
];