/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LearnIslamRequestStatus } from './learn-islam-request-status';

/**
 * Each possible value of `LearnIslamRequestStatus`
 */
export const LEARN_ISLAM_REQUEST_STATUS: LearnIslamRequestStatus[] = [
  0,
  1,
  2,
  3
];