/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LearnIslamKnowledgeLevel } from './learn-islam-knowledge-level';

/**
 * Each possible value of `LearnIslamKnowledgeLevel`
 */
export const LEARN_ISLAM_KNOWLEDGE_LEVEL: LearnIslamKnowledgeLevel[] = [
  0,
  1,
  2,
  3
];