/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LessonType } from './lesson-type';

/**
 * Each possible value of `LessonType`
 */
export const LESSON_TYPE: LessonType[] = [
  1,
  2,
  3,
  4
];