/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LevelDifficulty } from './level-difficulty';

/**
 * Each possible value of `LevelDifficulty`
 */
export const LEVEL_DIFFICULTY: LevelDifficulty[] = [
  1,
  2,
  3,
  4
];