/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeetingInquiryTopic } from './meeting-inquiry-topic';

/**
 * Each possible value of `MeetingInquiryTopic`
 */
export const MEETING_INQUIRY_TOPIC: MeetingInquiryTopic[] = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8
];