/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeetingInquiryRequestStatus } from './meeting-inquiry-request-status';

/**
 * Each possible value of `MeetingInquiryRequestStatus`
 */
export const MEETING_INQUIRY_REQUEST_STATUS: MeetingInquiryRequestStatus[] = [
  1,
  2,
  3,
  4,
  5
];