/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from '../models/language';
export interface QaTranslationInput {
  answerText?: string;
  answerTextJson?: string | null;
  language?: Language;
  questionText?: string;
}
