/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizTargetType } from './quiz-target-type';

/**
 * Each possible value of `QuizTargetType`
 */
export const QUIZ_TARGET_TYPE: QuizTargetType[] = [
  1,
  2,
  3
];