/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReligiousStatus } from './religious-status';

/**
 * Each possible value of `ReligiousStatus`
 */
export const RELIGIOUS_STATUS: ReligiousStatus[] = [
  1,
  2,
  3
];