/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportReason } from './report-reason';

/**
 * Each possible value of `ReportReason`
 */
export const REPORT_REASON: ReportReason[] = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  99
];