/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportType } from './report-type';

/**
 * Each possible value of `ReportType`
 */
export const REPORT_TYPE: ReportType[] = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  99
];