/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportStatus } from './report-status';

/**
 * Each possible value of `ReportStatus`
 */
export const REPORT_STATUS: ReportStatus[] = [
  1,
  2,
  3,
  4
];