/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendNotificationCommand {
  actionUrl?: string | null;
  customData?: ({
[key: string]: string;
}) | null;
  imageUrl?: string | null;
  message?: string;
  title?: string;
  userId?: string;
}
