/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface SendRoleBasedNotificationCommand {
  actionUrl?: string | null;
  customData?: ({
[key: string]: string;
}) | null;
  imageUrl?: string | null;
  message?: string;
  role?: UserRole;
  title?: string;
}
