/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnrollmentStatus } from '../models/enrollment-status';
export interface UpdateEnrollmentStatusCommand {
  status?: EnrollmentStatus;
}
