/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormFieldType } from '../models/form-field-type';
import { UpdateFormFieldOptionCommand } from '../models/update-form-field-option-command';
export interface UpdateFormFieldCommand {
  id?: string | null;
  isRequired?: boolean;
  label?: string;
  options?: Array<UpdateFormFieldOptionCommand>;
  order?: number;
  type?: FormFieldType;
}
