/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAchievementCommand {
  activeVolunteers?: number;
  coursesCompleted?: number;
  dialogues?: number;
  eventsHeld?: number;
  newMuslims?: number;
  socialMediaReach?: number;
}
