/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LessonType } from '../models/lesson-type';
export interface UpdateLessonCommand {
  contentJson?: string | null;
  contentUrl?: string | null;
  courseId?: string;
  description?: string | null;
  isPublished?: boolean;
  order?: number;
  thumbnailUrl?: string | null;
  title?: string;
  transcript?: string | null;
  type?: LessonType;
}
