/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCourseCommand {
  description?: string | null;
  isPublished?: boolean;
  levelId?: string;
  order?: number;
  tagIds?: Array<string>;
  thumbnailUrl?: string | null;
  title?: string;
}
