/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePreacherProfileCommand {
  bio?: string | null;
  certifications?: string | null;
  firstName?: string | null;
  imageUrl?: string | null;
  lastName?: string | null;
  linkedInProfile?: string | null;
  organization?: string | null;
  phoneNumber?: string | null;
  specialization?: string | null;
  website?: string | null;
  yearsOfExperience?: number | null;
}
