/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizTargetType } from '../models/quiz-target-type';
export interface UpdateQuizCommand {
  courseId?: string | null;
  lessonId?: string | null;
  levelId?: string | null;
  targetType?: QuizTargetType;
  title?: string;
  totalMarks?: number;
}
