/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeetingInquiryRequestStatus } from '../models/meeting-inquiry-request-status';
export interface UpdateInquiryRequestStatusCommand {
  status?: MeetingInquiryRequestStatus;
}
