/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LearnIslamRequestStatus } from '../models/learn-islam-request-status';
export interface UpdateLearnIslamRequestStatusCommand {
  id?: string;
  status?: LearnIslamRequestStatus;
}
