/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventRegistrationStatus } from '../models/event-registration-status';
export interface UpdateEventRegistrationStatusCommand {
  status?: EventRegistrationStatus;
}
