/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateFormFieldOptionCommand {
  id?: string | null;
  label?: string;
  order?: number;
  value?: string;
}
