/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateEventCommand {
  description?: string | null;
  endDateTime?: string;
  imageUrl?: string | null;
  isPublished?: boolean;
  meetingLink?: string | null;
  speakerName?: string | null;
  startDateTime?: string;
  title?: string;
}
