/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permission } from '../models/permission';
export interface UpdateUserPermissionsCommand {
  notes?: string | null;
  permissionNames?: Array<string> | null;
  permissions?: Permission | null;
}
