/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateQaTranslationInput } from '../models/update-qa-translation-input';
export interface UpdateQaCommand {
  isPublished?: boolean;
  tagIds?: Array<string>;
  translations?: Array<UpdateQaTranslationInput>;
}
