/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventStatus } from '../models/event-status';
export interface UpdateEventRegistrationStatusCommand {
  status?: EventStatus;
}
