/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportStatus } from '../models/report-status';
export interface UpdateReportStatusCommand {
  id?: string;
  reviewNotes?: string | null;
  status?: ReportStatus;
}
