/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReligiousStatus } from '../models/religious-status';
export interface UpdateStudentProfileCommand {
  address?: string | null;
  bio?: string | null;
  country?: string | null;
  countryCode?: string | null;
  dateOfBirth?: string | null;
  dateOfIslamConversion?: string | null;
  firstName?: string | null;
  gender?: string | null;
  imageUrl?: string | null;
  languages?: Array<number> | null;
  lastName?: string | null;
  oldReligion?: string | null;
  phoneNumber?: string | null;
  reasonForConversion?: string | null;
  reasonOfReligion?: string | null;
  religionStatus?: ReligiousStatus | null;
}
