/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Language } from '../models/language';
import { LevelDifficulty } from '../models/level-difficulty';
export interface UpdateLevelCommand {
  description?: string | null;
  difficulty?: LevelDifficulty;
  isPublished?: boolean;
  language?: Language;
  order?: number;
  title?: string;
}
