/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import type { Language } from './language';

export interface UpdateStudentProfileCommand {
  address?: string | null;
  bio?: string | null;
  country?: string | null;
  countryCode?: string | null;
  dateOfBirth?: string | null;
  dateOfIslamConversion?: string | null;
  firstName?: string | null;
  imageUrl?: string | null;
  lastName?: string | null;
  oldReligion?: string | null;
  languages?: Language[] | null;
  phoneNumber?: string | null;
  reasonForConversion?: string | null;
  reasonOfReligion?: string | null;
}
