/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAdminProfileCommand {
  bio?: string | null;
  department?: string | null;
  firstName?: string | null;
  imageUrl?: string | null;
  lastName?: string | null;
  phoneNumber?: string | null;
}
