/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMosqueCommand {
  address?: string | null;
  city?: string | null;
  country?: string | null;
  description?: string | null;
  district?: string | null;
  email?: string | null;
  googleMapsUrl?: string | null;
  governorate?: string | null;
  hasFridayKhutbah?: boolean;
  hasWomenPrayerArea?: boolean;
  imamName?: string | null;
  isActive?: boolean;
  latitude?: number | null;
  longitude?: number | null;
  mainImageUrl?: string | null;
  name?: string;
  phoneNumber?: string | null;
  websiteUrl?: string | null;
}
