/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateFormFieldCommand } from '../models/update-form-field-command';
export interface UpdateFormCommand {
  description?: string | null;
  fields?: Array<UpdateFormFieldCommand>;
  id?: string;
  isPublished?: boolean;
  title?: string;
}
