/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VolunteerType } from './volunteer-type';

/**
 * Each possible value of `VolunteerType`
 */
export const VOLUNTEER_TYPE: VolunteerType[] = [
  0,
  1,
  2,
  3,
  4,
  5
];