/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ResyncChannel$Params {
  channelId: string;
  maxVideos?: number;
}

export function resyncChannel(http: HttpClient, rootUrl: string, params: ResyncChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, resyncChannel.PATH, 'post');
  if (params) {
    rb.path('channelId', params.channelId, {});
    rb.query('maxVideos', params.maxVideos, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

resyncChannel.PATH = '/api/MuslimTube/channels/{channelId}/resync';
