/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateRolePermissionsCommand } from '../../models/update-role-permissions-command';
import { UserRole } from '../../models/user-role';

export interface UpdateRolePermissions$Params {
  role: UserRole;
      body: UpdateRolePermissionsCommand
}

export function updateRolePermissions(http: HttpClient, rootUrl: string, params: UpdateRolePermissions$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateRolePermissions.PATH, 'put');
  if (params) {
    rb.path('role', params.role, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

updateRolePermissions.PATH = '/api/Permissions/roles/{role}';
