/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuizTargetType } from '../../models/quiz-target-type';

export interface GetQuizzesWithPagination$Params {
  LevelId?: string | null;
  CourseId?: string | null;
  LessonId?: string | null;
  TargetType?: QuizTargetType | null;
  PageNumber?: number | null;
  PageSize?: number | null;
  SearchTerm?: string | null;
}

export function getQuizzesWithPagination(http: HttpClient, rootUrl: string, params?: GetQuizzesWithPagination$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getQuizzesWithPagination.PATH, 'get');
  if (params) {
    rb.query('LevelId', params.LevelId, {});
    rb.query('CourseId', params.CourseId, {});
    rb.query('LessonId', params.LessonId, {});
    rb.query('TargetType', params.TargetType, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('SearchTerm', params.SearchTerm, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getQuizzesWithPagination.PATH = '/api/Quizzes';
