/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Language } from '../../models/language';

export interface GetQAsWithPagination$Params {
  pageNumber?: number | null;
  pageSize?: number | null;
  searchTerm?: string | null;
  isPublished?: boolean | null;
  language?: Language | null;
  tagIds?: Array<string> | null;
}

export function getQAsWithPagination(http: HttpClient, rootUrl: string, params?: GetQAsWithPagination$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getQAsWithPagination.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('searchTerm', params.searchTerm, {});
    rb.query('isPublished', params.isPublished, {});
    rb.query('language', params.language, {});
    rb.query('tagIds', params.tagIds, {"style":"form","explode":true});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getQAsWithPagination.PATH = '/api/QAs';
