/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingInquiryRequestStatus } from '../../models/meeting-inquiry-request-status';
import { MeetingInquiryTopic } from '../../models/meeting-inquiry-topic';

export interface GetAll2$Params {
  Status?: MeetingInquiryRequestStatus | null;
  Topic?: MeetingInquiryTopic | null;
  IsAssigned?: boolean | null;
  PageNumber?: number | null;
  PageSize?: number | null;
  SearchTerm?: string | null;
}

export function getAll2(http: HttpClient, rootUrl: string, params?: GetAll2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getAll2.PATH, 'get');
  if (params) {
    rb.query('Status', params.Status, {});
    rb.query('Topic', params.Topic, {});
    rb.query('IsAssigned', params.IsAssigned, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('SearchTerm', params.SearchTerm, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getAll2.PATH = '/api/MeetingRequests';
