/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingInquiryRequestStatus } from '../../models/meeting-inquiry-request-status';

export interface GetByRequester2$Params {
  requesterId: string;
  status?: MeetingInquiryRequestStatus | null;
}

export function getByRequester2(http: HttpClient, rootUrl: string, params: GetByRequester2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, getByRequester2.PATH, 'get');
  if (params) {
    rb.path('requesterId', params.requesterId, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

getByRequester2.PATH = '/api/MeetingRequests/by-requester/{requesterId}';
