/* eslint-disable @typescript-eslint/no-explicit-any */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginWithFacebookCommand } from '../../models/login-with-facebook-command';
import { ResultOfAuthenticationResponse } from '../../models/result-of-authentication-response';

export interface LoginWithFacebook$Params {
  body: LoginWithFacebookCommand
}

export function loginWithFacebook(http: HttpClient, rootUrl: string, params: LoginWithFacebook$Params, context?: HttpContext): Observable<StrictHttpResponse<ResultOfAuthenticationResponse>> {
  const rb = new RequestBuilder(rootUrl, loginWithFacebook.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResultOfAuthenticationResponse>;
    })
  );
}

loginWithFacebook.PATH = '/api/Authentication/login/facebook';
