/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/naming-convention */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Result } from '../../models/result';

export interface LogoutParams {
}

export function logout(http: HttpClient, rootUrl: string, _params?: LogoutParams, context?: HttpContext): Observable<StrictHttpResponse<Result>> {
  const rb = new RequestBuilder(rootUrl, logout.PATH, 'post');

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Result>;
    })
  );
}

logout.PATH = '/api/Authentication/logout';
