/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/naming-convention */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefreshTokenCommand } from '../../models/refresh-token-command';
import { ResultOfAuthenticationResponse } from '../../models/result-of-authentication-response';

export interface RefreshTokenParams {
  body: RefreshTokenCommand
}

export function refreshToken(http: HttpClient, rootUrl: string, params: RefreshTokenParams, context?: HttpContext): Observable<StrictHttpResponse<ResultOfAuthenticationResponse>> {
  const rb = new RequestBuilder(rootUrl, refreshToken.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResultOfAuthenticationResponse>;
    })
  );
}

refreshToken.PATH = '/api/Authentication/refresh-token';
