/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Result } from '../../models/result';
import { VerifyOtpCommand } from '../../models/verify-otp-command';

export interface VerifyRegistrationOtp$Params {
  body: VerifyOtpCommand;
}

export function verifyRegistrationOtp(
  http: HttpClient,
  rootUrl: string,
  params: VerifyRegistrationOtp$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Result>> {
  const rb = new RequestBuilder(
    rootUrl,
    verifyRegistrationOtp.PATH,
    'post',
  );
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Result>;
      }),
    );
}

verifyRegistrationOtp.PATH = '/api/Authentication/verify-registration-otp';
